Double the number of webservers

diff --git a/0x0F-load_balancer/0-custom_http_response_header b/0x0F-load_balancer/0-custom_http_response_header
--- a/0x0F-load_balancer/0-custom_http_response_header
+++ b/0x0F-load_balancer/0-custom_http_response_header
@@ -1,11 +1,17 @@
-#!/usr/bin/env bash
-# Customizing a 404-error_page
+#!/bin/bash
+# shellcheck disable=SC2154
+# Installs Nginx and creates an index.html page
+# Performing a "moved permanently redirection" (303)to github page
+# Create 404 custom error page
+# Configure Nginx to create/add a custom header with the hostname
+# Test configurations for syntax errors and restart nginx
 
 # Updating Packages before performing installations
-sudo apt-get update
-sudo apt-get install -y nginx
+# Install Nginx if it's not already installed
+sudo apt update
+sudo apt install -y nginx
 
-# Creating an index.html page
+# Creating an index.html page on the server with nginx
 echo "Hello World!" | sudo tee /var/www/html/index.html
 
 # Performing a "moved permanently redirection" (301)
@@ -18,11 +24,27 @@ new_string="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation 
 
 sudo sed -i "s/listen 80 default_server;/$new_string/" /etc/nginx/sites-enabled/default
 
-# Creating an HTTP response header
+# Creating a HTTP response header / Configure Nginx to add the custom header
 sudo sed -i "/server_name _/a add_header X-Served-By $HOSTNAME;" /etc/nginx/sites-enabled/default
+
+# Check if the sed command was successful
+if [ "$?" -eq 0 ]; then
+    echo "Custom header configuration successful."
+else
+    echo "Failed to configure custom header."
+    exit 1
+fi
 
 # Testing configurations for syntax errors
 sudo nginx -t
 
-# Restart nginx after implementing changes
-sudo service nginx restart
+# Restart Nginx to apply the changes
+sudo systemctl restart nginx
+
+# Check if the Nginx restart was successful
+if [ "$?" -eq 0 ]; then
+    echo "Nginx restarted successfully."
+else
+    echo "Failed to restart Nginx."
+    exit 1
+fi
