Double the number of webservers

diff --git a/0x0F-load_balancer/0-custom_http_response_header b/0x0F-load_balancer/0-custom_http_response_header
--- a/0x0F-load_balancer/0-custom_http_response_header
+++ b/0x0F-load_balancer/0-custom_http_response_header
@@ -27,8 +27,24 @@ sudo sed -i "s/listen 80 default_server;/$new_string/" /etc/nginx/sites-enabled/
 # Creating an HTTP response header
 sudo sed -i "/server_name _/a add_header X-Served-By $HOSTNAME;" /etc/nginx/sites-enabled/default
 
+# Check if the sed command was successful
+if [ "$?" -eq 0 ]; then
+    echo "Custom header configuration successful."
+else
+    echo "Failed to configure custom header."
+    exit 1
+fi
+
 # Testing configurations for syntax errors
 sudo nginx -t
 
 # Restart nginx after implementing changes
 sudo service nginx restart
+
+# Check if the Nginx restart was successful
+if [ "$?" -eq 0 ]; then
+    echo "Nginx restarted successfully."
+else
+    echo "Failed to restart Nginx."
+    exit 1
+fi
